import PDFDocument from "pdfkit";
import type { Response } from "express";
import type { EnglishContent, MathsContent } from "../drizzle/schema";

function formatDate(s: string): string {
  const d = new Date(s + "T12:00:00");
  return d.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
}

// ─── Shared layout constants (A4 in points: 595 × 842) ───────────────────────
const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

function drawHeader(
  doc: InstanceType<typeof PDFDocument>,
  studentName: string,
  subject: string,
  date: string,
  accentColor: string
) {
  // Accent bar
  doc.rect(0, 0, PAGE_W, 70).fill(accentColor);

  // Title
  doc
    .fillColor("#FFFFFF")
    .font("Helvetica-Bold")
    .fontSize(20)
    .text(`${studentName}'s ${subject === "maths" ? "Maths" : "English"} Worksheet`, MARGIN, 18, { width: CONTENT_W - 120 });

  // Date
  doc
    .fillColor("rgba(255,255,255,0.85)")
    .font("Helvetica")
    .fontSize(9)
    .text(formatDate(date), MARGIN, 44, { width: CONTENT_W });

  // Subject badge (right side)
  const badgeX = PAGE_W - MARGIN - 90;
  doc.roundedRect(badgeX, 18, 90, 28, 6).fillAndStroke("rgba(255,255,255,0.2)", "rgba(255,255,255,0.4)");
  doc
    .fillColor("#FFFFFF")
    .font("Helvetica-Bold")
    .fontSize(11)
    .text(subject === "maths" ? "MATHS" : "ENGLISH", badgeX, 26, { width: 90, align: "center" });

  doc.fillColor("#1E293B"); // reset fill
}

function drawFooter(doc: InstanceType<typeof PDFDocument>, pageNum: number, accentColor: string) {
  const y = PAGE_H - 35;
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor("#E2E8F0").lineWidth(0.5).stroke();
  doc
    .fillColor("#94A3B8")
    .font("Helvetica")
    .fontSize(8)
    .text("Daily Worksheets · Generated by AI · British Curriculum", MARGIN, y + 8, { width: CONTENT_W - 60, align: "left" });
  doc.text(`Page ${pageNum}`, MARGIN, y + 8, { width: CONTENT_W, align: "right" });
}

// ─── Maths PDF ────────────────────────────────────────────────────────────────
export function generateMathsPDF(
  res: Response,
  studentName: string,
  date: string,
  content: MathsContent
) {
  const accentColor = studentName.toLowerCase() === "samson" ? "#7C3AED" : "#0891B2";
  const doc = new PDFDocument({ size: "A4", margin: MARGIN, bufferPages: true });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${studentName}-Maths-${date}.pdf"`
  );
  doc.pipe(res);

  let pageNum = 1;
  drawHeader(doc, studentName, "maths", date, accentColor);

  let y = 90;

  // Topic heading
  if (content.topic) {
    doc
      .fillColor(accentColor)
      .font("Helvetica-Bold")
      .fontSize(13)
      .text(`Topic: ${content.topic}`, MARGIN, y);
    y += 22;
  }

  // Instructions
  doc
    .fillColor("#64748B")
    .font("Helvetica-Oblique")
    .fontSize(9)
    .text(
      "Answer all questions. Show your working out clearly. Check your answers when you have finished.",
      MARGIN,
      y,
      { width: CONTENT_W }
    );
  y += 22;

  // Divider
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor("#E2E8F0").lineWidth(0.5).stroke();
  y += 12;

  const questions = content.questions ?? [];

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const qText = `${q.id}.  ${q.text}`;

    // Estimate height needed
    doc.fontSize(11);
    const textHeight = doc.heightOfString(qText, { width: CONTENT_W - 30 });
    const rowHeight = Math.max(textHeight + 8, 28);
    const answerLineH = 22;
    const totalH = rowHeight + answerLineH + 6;

    // Page break check
    if (y + totalH > PAGE_H - 60) {
      drawFooter(doc, pageNum, accentColor);
      doc.addPage();
      pageNum++;
      drawHeader(doc, studentName, "maths", date, accentColor);
      y = 90;
    }

    // Alternating row background
    if (i % 2 === 0) {
      doc.rect(MARGIN - 6, y - 4, CONTENT_W + 12, rowHeight + 4).fill("#F8FAFC");
    }

    // Question number circle
    doc.circle(MARGIN + 10, y + 8, 9).fill(accentColor);
    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(8).text(String(q.id), MARGIN + 4, y + 4, { width: 14, align: "center" });

    // Question text
    doc
      .fillColor("#1E293B")
      .font("Helvetica")
      .fontSize(11)
      .text(q.text, MARGIN + 26, y, { width: CONTENT_W - 30 });

    y += rowHeight;

    // Answer line
    doc
      .moveTo(MARGIN + 26, y + 14)
      .lineTo(PAGE_W - MARGIN, y + 14)
      .strokeColor("#CBD5E1")
      .lineWidth(0.4)
      .stroke();
    doc.fillColor("#94A3B8").font("Helvetica").fontSize(7).text("Answer:", MARGIN + 26, y + 6);

    y += answerLineH + 10;
  }

  drawFooter(doc, pageNum, accentColor);
  doc.end();
}

// ─── English PDF ──────────────────────────────────────────────────────────────
export function generateEnglishPDF(
  res: Response,
  studentName: string,
  date: string,
  content: EnglishContent
) {
  const accentColor = studentName.toLowerCase() === "samson" ? "#7C3AED" : "#0891B2";
  const doc = new PDFDocument({ size: "A4", margin: MARGIN, bufferPages: true });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${studentName}-English-${date}.pdf"`
  );
  doc.pipe(res);

  let pageNum = 1;
  drawHeader(doc, studentName, "english", date, accentColor);

  let y = 90;

  // Prompt type badge
  doc
    .roundedRect(MARGIN, y, 120, 20, 4)
    .fill(accentColor + "20");
  doc
    .fillColor(accentColor)
    .font("Helvetica-Bold")
    .fontSize(9)
    .text(content.promptType.toUpperCase(), MARGIN + 6, y + 5, { width: 108 });
  y += 30;

  // Title
  doc
    .fillColor("#1E293B")
    .font("Helvetica-Bold")
    .fontSize(16)
    .text(content.title, MARGIN, y, { width: CONTENT_W });
  y += doc.heightOfString(content.title, { width: CONTENT_W }) + 14;

  // Prompt box
  doc.fontSize(11);
  const promptH = doc.heightOfString(content.prompt, { width: CONTENT_W - 20 }) + 20;
  doc.roundedRect(MARGIN, y, CONTENT_W, promptH, 8).fill("#F0FDF4");
  doc.roundedRect(MARGIN, y, 4, promptH, 2).fill("#10B981");
  doc
    .fillColor("#1E293B")
    .font("Helvetica")
    .fontSize(11)
    .text(content.prompt, MARGIN + 14, y + 10, { width: CONTENT_W - 20 });
  y += promptH + 16;

  // Hints
  if (content.hints && content.hints.length > 0) {
    doc
      .fillColor("#475569")
      .font("Helvetica-Bold")
      .fontSize(10)
      .text("Writing Hints:", MARGIN, y);
    y += 16;
    for (const hint of content.hints) {
      doc.fontSize(10);
      const hintH = doc.heightOfString(`• ${hint}`, { width: CONTENT_W - 16 });
      doc
        .fillColor("#64748B")
        .font("Helvetica")
        .fontSize(10)
        .text(`•  ${hint}`, MARGIN + 8, y, { width: CONTENT_W - 16 });
      y += hintH + 6;
    }
    y += 8;
  }

  // Vocabulary words
  if (content.vocabularyWords && content.vocabularyWords.length > 0) {
    doc
      .fillColor("#475569")
      .font("Helvetica-Bold")
      .fontSize(10)
      .text("Vocabulary to use:", MARGIN, y);
    y += 14;
    let vx = MARGIN;
    for (const word of content.vocabularyWords) {
      doc.fontSize(9);
      const ww = doc.widthOfString(word) + 16;
      if (vx + ww > PAGE_W - MARGIN) { vx = MARGIN; y += 22; }
      doc.roundedRect(vx, y, ww, 18, 4).fill(accentColor + "15");
      doc.fillColor(accentColor).font("Helvetica-Bold").fontSize(9).text(word, vx + 8, y + 4, { width: ww - 16 });
      vx += ww + 6;
    }
    y += 28;
  }

  // Writing lines
  if (y + 60 > PAGE_H - 60) {
    drawFooter(doc, pageNum, accentColor);
    doc.addPage();
    pageNum++;
    y = MARGIN;
  }

  doc
    .fillColor("#94A3B8")
    .font("Helvetica-Oblique")
    .fontSize(9)
    .text("Write your response below:", MARGIN, y);
  y += 18;

  const lineSpacing = 28;
  const linesAvailable = Math.floor((PAGE_H - 60 - y) / lineSpacing);
  const totalLines = Math.max(linesAvailable, 14);

  for (let i = 0; i < totalLines; i++) {
    if (y + lineSpacing > PAGE_H - 60) {
      drawFooter(doc, pageNum, accentColor);
      doc.addPage();
      pageNum++;
      y = MARGIN;
    }
    doc
      .moveTo(MARGIN, y + lineSpacing - 4)
      .lineTo(PAGE_W - MARGIN, y + lineSpacing - 4)
      .strokeColor("#E2E8F0")
      .lineWidth(0.4)
      .stroke();
    y += lineSpacing;
  }

  drawFooter(doc, pageNum, accentColor);
  doc.end();
}
